default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.15.20
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.13.1-1
  hooks:
    # Choose one of:
    - id: shfmt         # prebuilt upstream executable
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.16.4
  hooks:
    - id: commitizen
      stages: [commit-msg]
