---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: firefly-iii-dkb
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import
            image: ghcr.io/devfaz/firefly-iii-dkb:latest@sha256:8acd8d9229b1a5ceb17438b6020bcd2540880301a3a0e4aedc564f86b4c3bd1a
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: "/home/aqbanking/.aqbanking"
              name: aqbanking-data
          restartPolicy: OnFailure
          volumes:
            - name: aqbanking-data
              persistentVolumeClaim:
                claimName: firefly-iii-dkb-pvc
