---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: firefly-iii-dkb
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import
            image: ghcr.io/devfaz/firefly-iii-dkb:latest@sha256:eb113157898cf69d298368536b43bd525b1c9c0671bc578f060a1037ad04aadc
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: "/home/aqbanking/.aqbanking"
              name: aqbanking-data
          restartPolicy: OnFailure
          volumes:
            - name: aqbanking-data
              persistentVolumeClaim:
                claimName: firefly-iii-dkb-pvc
