---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: firefly-iii-dkb
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import
            image: ghcr.io/devfaz/firefly-iii-dkb:latest@sha256:675f8fb06987b6975c9ea1a07d8735cb7d955f4ae9c8d84e31bc9cb4fb3d345d
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: "/home/aqbanking/.aqbanking"
              name: aqbanking-data
          restartPolicy: OnFailure
          volumes:
            - name: aqbanking-data
              persistentVolumeClaim:
                claimName: firefly-iii-dkb-pvc
