---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: firefly-iii-dkb
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import
            image: ghcr.io/devfaz/firefly-iii-dkb:latest@sha256:8864f7c55894c1ac3e4cec6d395d08ac99ab776ba4e3fc24ca14b35dbee418c2
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: "/home/aqbanking/.aqbanking"
              name: aqbanking-data
          restartPolicy: OnFailure
          volumes:
            - name: aqbanking-data
              persistentVolumeClaim:
                claimName: firefly-iii-dkb-pvc
