---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: firefly-iii-dkb
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import
            image: ghcr.io/devfaz/firefly-iii-dkb:latest@sha256:c63f45a0671bbe958ac3d9b807a96f758522ec58b0f074c3cd36ecb766fc3985
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: "/home/aqbanking/.aqbanking"
              name: aqbanking-data
          restartPolicy: OnFailure
          volumes:
            - name: aqbanking-data
              persistentVolumeClaim:
                claimName: firefly-iii-dkb-pvc
