on:
  push:
    branches:
      - main
env:
  IMAGE: ghcr.io/devfaz/firefly-iii-dkb
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: docker
    container:
      image: node:25-trixie@sha256:7a99c607c2a73ea54f8c554d10bc790569fb7d1173638d5a9f56a23923fe2f87
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - name: Prepare
        run: |-
          export DEBIAN_FRONTEND=noninteractive
          set -e -o pipefail -u
          apt -qqy update
          apt -qqy install docker.io
          echo ${{ secrets.MY_GITHUB_TOKEN }} | docker login --username devfaz --password-stdin $REGISTRY
          docker build -q -t ${IMAGE}:latest .
      - name: Setup Node.js
        uses: https://data.forgejo.org/actions/setup-node@v6
        with:
          node-version: "lts/*"          
      - name: Release
        run: |-
          npm install @semantic-release/exec -D
          npx semantic-release